version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  envoy:
    image: envoyproxy/envoy:v1.32.1
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy_logs:/var/log/envoy  # Map host directory to container log directory
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on:
      - nginx
