version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_logs:/var/log/nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  apache:
    image: httpd:latest
    container_name: apache
    volumes:
      - ./apache_logs:/usr/local/apache2/logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  envoy:
    image: envoyproxy/envoy:v1.32.1
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy_logs:/var/log/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on:
      - nginx
      - apache
