receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # Endpoint to receive OTLP data from Envoy

processors:
  batch:  # Adds batching of data to reduce the number of outgoing requests
    timeout: 1s
    send_batch_size: 1024

exporters:
  #file:
  #  path: ./otel-logs.json  # File exporter to save logs
  #  rotation:
  #    max_size_megabytes: 10
  #    max_backup_count: 5

  debug:
    verbosity: detailed  # Console logging for debugging and verification

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
